### ISSUE TITLE
Create sphinx documentation

### ISSUE THREAD

**Issue by Rafiot** [Lookyloo/ScrapySplashWrapper#5]
Quite a few of the methods are documented, but we do not generate the documentation.

See https://www.sphinx-doc.org/en/master/usage/quickstart.html

And in order to publish it on read the docs: https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html

**Comment by hjanday** [comment]
Do I just make docs for Scrapy? I'm a beginner and I'd like to lend a hand

**Comment by Rafiot** [comment]
`ScrapySplashWrapper`'s code is (very partially) documented, but it would be nice to setup the automatic generation of the documentation on read the doc.

The goal is to generate something similar to what we have there: https://github.com/MISP/PyMISP/tree/main/docs/source

And while we're at it, adding comments in `ScrapySplashWrapper`'s code would be good.
